#!/usr/bin/env fish

mkdir -p src/days

echo -e "#![allow(unused_variables)]\n" >src/days/mod.rs

for day in (seq 1 24)
    echo "pub(crate) mod day$day;" >>src/days/mod.rs
    echo 'pub(crate) fn part1(input: String) {
    unimplemented!("This puzzle has not been completed yet!");
}

pub(crate) fn part2(input: String) {
    unimplemented!("This puzzle has not been completed yet!");
}' >src/days/day$day.rs
end

echo "pub(crate) mod day25;" >>src/days/mod.rs

echo 'pub(crate) fn part1(input: String) {
    unimplemented!("This puzzle has not been completed yet!");
}

pub(crate) fn part2(input: String) {
    unimplemented!("Advent of Code puzzles do not have a part 2 on Christmas Day!");
}' >src/days/day25.rs